### ISSUE TITLE
How to resize and upload images?

### ISSUE THREAD

**Issue by lmk378** [abhay-ramesh/next-s3-uploader#6]
Function "uploadFiles" working with "File[]" or "FileList". With react-image-file-resizer resized "File[]" not working.

**Comment by lmk378** [comment]
> Function "uploadFiles" working with "File[]" or "FileList". With react-image-file-resizer resized "File[]" not working.

Works fine with browser-image-compression.

**Comment by abhay-ramesh** [comment]
@lmk378 Could you elaborate the issue and how it was caused? Cause `File[]` and `FileList[]` are the returned types from file input fields.

And if you need any feature from this library please do let me know.

Thank you for contributing to the community.
